jnwatson/py-lmdb

lmdb/__init__.py
lmdb/tool.py

Two small bug fixes:
- py-lmdb did not work in the context of embedded python (commit 08e7ff28efc47022436d9e6f120f2541a39dbc6e)
- Deletion from command line did not work (commit 4acac93b9b1ab3a27c7ef7597b645d9868704d7d)

Embedded python fix and fix for deletion by key

---

ChangeLog
lib/lmdb.h
lib/mdb.c
lib/midl.c
lib/midl.h

LMDB_0.9.70

---

lmdb/tool.py

Fix https://github.com/dw/py-lmdb/issues/127

---

ChangeLog
lmdb/__init__.py
lmdb/tool.py

Resolves https://github.com/dw/py-lmdb/issues/177, and an -x 2.7 bug.

Fix 2/3 tool bugs

---

examples/address-book.py

Just a simple fixup to get `address-book.py` running under Py3.
Something better would be some kind of encoding story for lmdb?

Update address-book.py for python3

---

.travis.yml
README.md
appveyor.yml
docs/index.rst

Drop testing for 3.3 due to CI dropping support, add testing for 3.7

Update readme, CI

---

docs/index.rst
lmdb/__init__.py
lmdb/cffi.py
lmdb/cpython.c
tests/cursor_test.py
tests/testlib.py

Preload the value only if it is going to be used

---

lmdb/cpython.c
tests/crash_test.py

Resolves https://github.com/jnwatson/py-lmdb/issues/216

Fix crash under debug cpython when mdb_cursor_open failed

---

lmdb/tool.py

Fix -l lmdb invocation

---

docs/index.rst
lmdb/cffi.py
lmdb/cpython.c
tests/package_test.py

Add _Database to the generated docs

---

docs/index.rst

Add note about what happens when writemap=True and run out of disk.

---

docs/index.rst
lmdb/cffi.py

Resolves https://github.com/jnwatson/py-lmdb/issues/254

Correct documentation on env.stat

---

.travis.yml
tests/cursor_test.py

Get pypy3 passing tests

---

lib/lmdb.h
lib/mdb.c
lib/midl.c
lib/midl.h
lib/py-lmdb/env-copy-txn.patch
setup.py

Copy from https://git.openldap.org/openldap/openldap.git, tag LMDB_0.9.27

Upgrade to LMDB 0.9.27

---

lib/lmdb.h
lib/mdb.c
lib/py-lmdb/env-copy-txn.patch
tests/cursor_test.py

0.9.27 has a iter/delete defect demonstrated in testIterwithDeletes

Downgrade from LMDB 0.9.27 to  0.9.26

---

lmdb/cffi.py
lmdb/cpython.c
tests/cursor_test.py
tests/txn_test.py

Allow passing None as value to transaction.del, fix cursor.put dupsort with append behavior

---

.github/workflows/python-package.yml
tests/cursor_test.py

Added linux aarch64 wheel build support.
Related to https://github.com/jnwatson/py-lmdb/issues/298. @jnwatson Could you please review this PR?

Add linux aarch64 wheel build support

---

.github/workflows/python-package.yml
README.md
lmdb/cpython.c
tests/cursor_test.py
tests/env_test.py

Spare txn fix

---

.github/workflows/python-package.yml

Accidentally left out.
Credit to vEpiphyte for solution.

Add python 3.11 to manylinux distribution

---

.github/workflows/python-package.yml

Github Actions deprecated ubuntu-18.04. Replace with ubuntu-latest

Attempt to overcome CI deprecation

---

.github/workflows/python-package.yml
lib/lmdb.h
lib/mdb.c
lib/midl.h
lib/py-lmdb/env-copy-txn.patch
lib/py-lmdb/its-10346.patch
setup.py

Also cherry-pick [a fix to OpenLDAP ITS#10346](https://git.openldap.org/openldap/openldap/-/commit/900756902a98644b94f44b41b22251287c6cde24).

Update to lmdb 0.9.33

---

.github/workflows/python-package.yml
pyproject.toml
setup.py

Also remove some end-of-life stuff

Completely redo CI
