- docs/index.rst
I got stuck following this example, so I figured this could avoid future confusion.
> Fixed typos in code example in the docs.

- docs/index.rst
- lmdb/__init__.py
- lmdb/cffi.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- .travis.yml
- lmdb/cffi.py
- lmdb/cpython.c
- misc/helpers.sh
- misc/runtests-travisci.sh
- misc/runtests-ubuntu-12-04.sh
Managed to refactor tests while keeping python2.5 support by piggybacking it on python2.6 environment.
Both 2.5 and 2.6 tests will be run with the legacy test scripts, while the rest of the versions will fall under the new structure for .travis.yml
> Make Travis-CI green

- lmdb/cffi.py
In the cffi bindings, `next_nodup` was calling `mdb_cursor_get` with `MDB_PREV_NODUP`, rather than `MDB_NEXT_NODUP` as expected.
> Fix bug with next_nodup in cffi bindings

- .travis.yml
The travis build had some remaining 3.2 special cases.
Remove them, since 3.2 is no longer being built.
> Remove Py3.2 remnants

- lmdb/cffi.py
- lmdb/cpython.c
Instead of checking if the directory exists and creating it if not, try
to create it and handle the error.
> More correct and simpler mkdir() usage

- lmdb/cffi.py
- tests/txn_test.py
Currently there is an issue with the CFFI module and the database 'drop' method. Once you have dropped a named database within an environment, that name cannot be used again without first closing the environment.
I've added a test "test_double_delete" that highlights the issue, this passes on cpython but fails for pypy.
Then there is one minor change to "drop" which simply updates the "_dbs" dictionary that the environment is using to keep track of open databases. Essentially drop was closing the database as far as lmdb was concerned but leaving open a reference within py-lmdb.
(all tests pass for cpython and pypy with this applied)
> Fix ns polution for drop

- lmdb/__init__.py
When using [JEP](https://github.com/ninia/jep), the `sys.argv` property exists but is empty. Raising index out of bounds for `sys.argv[0]`.
This fix should address that.
> fix argv check in jep environment

- lmdb/cpython.c
> Solaris needs ```#include "python.h"``` as soon as possible #213

- lmdb/tool.py
- tests/testlib.py
- tests/tool_test.py
Resolves #219.
Fix missing bytes encoding in parameter to rewrite command and the default --env option
Add regression tests for both.
> Fix lmdb.tool database encoding for Python3

- lib/py-lmdb/preload.h
- lmdb/cffi.py
- lmdb/cpython.c
- tests/cursor_test.py
- tests/txn_test.py
Previously, cursor.putmulti failed to use the right LMDB parameter to put when append=True. Now it will automatically use MDB_APPENDDUP when the database is dupsort.
Resolves #235.
> Resolve Dupsort putmulti append=True bug

- lmdb/cffi.py
- lmdb/cpython.c
- tests/env_test.py
The txn argument was unused but validated.  It is now not validated. The flags method now takes 0 or 1 arguments.
Resolves #239.
> Allow _Database.flags to take no arguments

- lmdb/cpython.c
- tests/cursor_test.py
- tests/env_test.py
- tests/testlib.py
Change initialization order to avoid partially constructed objects.
Fix minor uninitialized memory issue when accessing the key or the value of an unpositioned cursor.
Resolves #245
> Partial object rejigger

- .travis.yml
- appveyor.yml
- docs/index.rst
- lib/py-lmdb/env-copy-txn.patch
- lmdb/cffi.py
- lmdb/cpython.c
- setup.py
- tests/env_test.py
This is implemented with a patch to the underlying LMDB library.
> Allow environment copy to be executed against a passed-in transaction

- lmdb/cpython.c
Previously, using getmulti() with dupfixed_bytes would ignore the as_buffer argument and always return values. This _should_ work now (but I did not write extra tests for it).
Also, there are still some WIP-type comments in that function. If this is not going to be scrutinized further, please let me know, and I'll just remove them and squash it into this commit.
> Complete as_buffer handling in Cursor.getmulti()

- lmdb/cffi.py
> Docs: Clarify `put` methods' `dupdata` and `append` parameters

- lmdb/cffi.py
- lmdb/cpython.c
Now, integerdup will automatically set dupfixed, and dupfixed
automatically sets dupsort.
Resolves #250
> Eliminate invalid DB flag combinations in open_db

- lmdb/cffi.py
- lmdb/cpython.c
- tests/getmulti_test.py
- tests/testlib.py
This adds an optimized codepath for marshaling getmulti() results into a NumPy array. In CPython it builds the structured array in a buffer and returns a memoryview to it. This is how to use it:
````
key_bytes, val_bytes = 4, 8
dtype = np.dtype([(f'S{key_bytes}', f'S{val_bytes}}')])
arr = np.frombuffer(
cur.getmulti(keys, dupdata=True, dupfixed_bytes=val_bytes, key_bytes=key_bytes)
)
````
With this option, I think the argument names should probably change to something more consistent, like `key_bytes`/`val_bytes`, `key_size`/`val_size`, `dupfixed_key_bytes`/`dupfixed_val_bytes`, etc.
> Optionally return structured array buffer for cursor.getmulti()

- .travis.yml
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing,We typically build applications for customers and ISVs, and while we don't use this package directly, 
we do count on all of the packages in debian/ubuntu to build other packages. So we more likely have this as a second or third level dependency and couldn't tell you explicitly which features we use or our usage model,For more info tag @gerrith3.
> Add poweron architecture ppc64le to travis build

- lmdb/cffi.py
- tests/cursor_test.py
Resolves #288.
The key was that creating the DB in read-only shouldn't use a spare transaction.
> Fix bug in CFFI creating a DB in read-only environment

- .github/workflows/python-package.yml
- tests/crash_test.py
Ubuntu on PPC64LE has a 64K page size.  This impacts the minimum map size for an environment, as well as how fast an environment fills up.
> Make map resize test more robust for weird-page-size OSs 

- lmdb/tool.py
While restoring, the cdbmake file is opened in binary mode and therefore `read()` returns byte-encoded characters. https://github.com/jnwatson/py-lmdb/blob/6591da5eef392f0cb2d60528e78bdc452a9b898f/lmdb/tool.py#L333-L336
Closes #303
> Use byte encoded strings in restore_cursor_from_fp

- lmdb/cffi.py
space and preceding d were swapped
> minor typo, visible in online documentation

- lmdb/cpython.c
Avoid using PyObject_AsReadBuffer, do what PyObject_AsReadBuffer does.
Note that this is not safe, and it has never been safe, but the code does *exactly* what it used to do (at least on Python 3.8+).
Fixes https://github.com/jnwatson/py-lmdb/issues/362
> Fix build with Python 3.13+

- setup.py
The CFFI build process was previously using absolute paths to the source and include directories, which caused the resulting wheel to be non-portable.
This commit uses relative paths instead. This ensures that the CFFI build process creates a portable wheel that can be installed on any machine.
> Fix: CFFI build now uses relative paths
